# Generated by Django 2.0.5 on 2018-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_passed', models.BooleanField(default=False)),
            ],
        ),
    ]
